#!/usr/bin/env bash
#
# bootstrap.sh - Interactive GCP Project Bootstrapper and Configuration Manager
#

set -euo pipefail

# Add default Windows Google Cloud SDK path to PATH if present (Git Bash or WSL)
if [ -d "/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin" ]; then
    export PATH="/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:$PATH"
elif [ -d "/mnt/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin" ]; then
    export PATH="/mnt/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:$PATH"
fi

# ANSI color codes for pretty logs
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}===============================================${NC}"
echo -e "${BLUE}   GCP SRE Agent Codelab Project Bootstrapper  ${NC}"
echo -e "${BLUE}===============================================${NC}"

# 1. Verify gcloud CLI is installed
if ! command -v gcloud &> /dev/null; then
    echo -e "${RED}Error: gcloud CLI is not installed.${NC}"
    echo "Please install the Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
    exit 1
fi
echo -e "${GREEN}✓ gcloud CLI is installed.${NC}"

# 2. Check auth status
ACTIVE_ACCOUNT=$(gcloud auth list --filter="status:ACTIVE" --format="value(account)" 2>/dev/null || true)
if [ -z "$ACTIVE_ACCOUNT" ]; then
    echo -e "${YELLOW}Warning: No active gcloud session detected.${NC}"
    echo "Launching gcloud auth login..."
    gcloud auth login
else
    echo -e "${GREEN}✓ Authenticated as: $ACTIVE_ACCOUNT${NC}"
fi

# 3. Retrieve default/current project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)

# 4. Prompt for Project ID
echo ""
if [ -n "$CURRENT_PROJECT" ]; then
    read -p "Enter GCP Project ID [default: $CURRENT_PROJECT]: " PROJECT_ID
    PROJECT_ID=${PROJECT_ID:-$CURRENT_PROJECT}
else
    read -p "Enter GCP Project ID: " PROJECT_ID
    if [ -z "$PROJECT_ID" ]; then
        echo -e "${RED}Error: Project ID cannot be empty.${NC}"
        exit 1
    fi
fi

# 5. Check if project exists or needs to be created
PROJECT_EXISTS=$(gcloud projects list --filter="projectId:$PROJECT_ID" --format="value(projectId)" 2>/dev/null || true)
if [ -z "$PROJECT_EXISTS" ]; then
    echo -e "${YELLOW}Project '$PROJECT_ID' does not exist in your account.${NC}"
    read -p "Would you like to create a new project named '$PROJECT_ID'? (y/n): " CREATE_PROJECT
    if [[ "$CREATE_PROJECT" =~ ^[Yy]$ ]]; then
        echo "Creating project '$PROJECT_ID'..."
        gcloud projects create "$PROJECT_ID" --set-as-default
        echo -e "${GREEN}✓ Project created successfully!${NC}"
    else
        echo -e "${RED}Bootstrapping aborted.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}✓ Using existing project: $PROJECT_ID${NC}"
    gcloud config set project "$PROJECT_ID"
fi

# 6. Make sure billing is enabled (Cloud Run, Cloud Build and Firestore all need it)
BILLING_ENABLED=$(gcloud billing projects describe "$PROJECT_ID" --format="value(billingEnabled)" 2>/dev/null || true)
if [ "$BILLING_ENABLED" != "True" ]; then
    echo -e "${YELLOW}Billing is not enabled for '$PROJECT_ID'.${NC}"
    echo "Open billing accounts you can use:"
    gcloud billing accounts list --filter="open=true" --format="table(name.basename(), displayName)" || true
    read -p "Enter the billing account ID to link (leave empty to skip): " BILLING_ACCOUNT
    if [ -n "$BILLING_ACCOUNT" ]; then
        gcloud billing projects link "$PROJECT_ID" --billing-account="$BILLING_ACCOUNT"
        echo -e "${GREEN}✓ Linked billing account $BILLING_ACCOUNT${NC}"
    else
        echo -e "${YELLOW}Skipped. deploy.sh will fail until billing is enabled for this project.${NC}"
    fi
else
    echo -e "${GREEN}✓ Billing is enabled.${NC}"
fi

# 7. Prompt for Region & Zone
echo ""
read -p "Enter preferred GCP Region [default: us-central1]: " REGION
REGION=${REGION:-us-central1}

read -p "Enter preferred GCP Zone [default: ${REGION}-a]: " ZONE
ZONE=${ZONE:-${REGION}-a}

# 8. Gemini API key (deploy.sh stores it in Secret Manager)
echo ""
if [ -n "${GEMINI_API_KEY:-}" ]; then
    echo -e "${GREEN}✓ Using GEMINI_API_KEY from your environment.${NC}"
else
    echo "deploy.sh needs a Gemini API key (create one at https://aistudio.google.com/apikey)."
    read -r -s -p "Enter GEMINI_API_KEY (input hidden): " GEMINI_API_KEY
    echo ""
    if [ -z "$GEMINI_API_KEY" ]; then
        echo -e "${YELLOW}No key entered. Add GEMINI_API_KEY=... to .env before running ./deploy.sh.${NC}"
    fi
fi

echo -e "${BLUE}-----------------------------------------------${NC}"
echo "Generating .env configuration file..."
umask 077  # .env holds the API key: keep it private
cat << EOF > .env
# SRE Agent Codelab Environment Configuration
# Generated by bootstrap.sh on $(date)

MOCK_GCP=false
GCP_PROJECT=$PROJECT_ID
GCP_REGION=$REGION
GCP_ZONE=$ZONE
GEMINI_API_KEY=$GEMINI_API_KEY
EOF

echo -e "${GREEN}✓ Configuration saved to '.env'${NC}"
echo -e "${BLUE}-----------------------------------------------${NC}"
echo -e "Next steps:"
echo -e "1. Run ${YELLOW}./deploy.sh${NC} to provision IAM service accounts and deploy to Cloud Run."
echo -e "2. Run ${YELLOW}uv run simulate_incident.py${NC} to execute local/mock simulations."
echo -e "${BLUE}===============================================${NC}"
