"""HTTP Service Wrapper for the Antigravity SRE Agent.

This module exposes a FastAPI application that wraps the Antigravity agent,
allowing it to be deployed to GCP Cloud Run and invoked via HTTP requests
(e.g., from alerting webhooks or chat platforms).
"""

import os
import logging
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from agent.config import load_agent_config, load_firestore_agent_config, Agent, HAS_ANTIGRAVITY

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("sre_agent_service")

# Initialize FastAPI application
app = FastAPI(
    title="Antigravity Cloud SRE Agent Service",
    description="A cloud-deployable SRE agent service wrapper running on Cloud Run.",
    version="0.1.0"
)

class DiagnoseRequest(BaseModel):
    """Pydantic model representing a diagnostic request.

    Attributes:
        prompt: The incident description or query for the SRE agent.
        project_id: Optional GCP Project ID to override default settings.
    """
    prompt: str
    project_id: str | None = None


class DiagnoseResponse(BaseModel):
    """Pydantic model representing the agent response.

    Attributes:
        status: The execution status (e.g., 'success').
        result: The diagnostic markdown report generated by the agent.
    """
    status: str
    result: str


class ChatRequest(BaseModel):
    """Pydantic model representing a stateful chat request.

    Attributes:
        prompt: The chat message for the SRE agent.
        conversation_id: Optional ID of an existing session to resume.
        project_id: Optional GCP Project ID to override default settings.
    """
    prompt: str
    conversation_id: str | None = None
    project_id: str | None = None


class ChatResponse(BaseModel):
    """Pydantic model representing a stateful chat response.

    Attributes:
        status: The execution status.
        response: The agent response text.
        conversation_id: The active session ID (useful for follow-up turns).
    """
    status: str
    response: str
    conversation_id: str | None = None


@app.get("/health")
async def health_check() -> dict[str, str]:
    """Basic health check endpoint.

    Returns:
        A dictionary containing the service health status.
    """
    return {"status": "healthy", "sdk_loaded": str(HAS_ANTIGRAVITY)}


@app.post("/diagnose")
async def diagnose(request: DiagnoseRequest) -> DiagnoseResponse:
    """Trigger the SRE agent diagnostics workflow.

    Initializes the SRE agent configuration, runs the agentic troubleshooting
    reasoning loop with safety policy gating, and returns the SRE diagnosis.

    Args:
        request: The DiagnoseRequest payload containing the prompt.

    Returns:
        DiagnoseResponse containing the markdown diagnostic report.
    """
    logger.info(f"Received SRE diagnostics request: {request.prompt}")

    # Set project ID in environment if provided to affect the tools
    if request.project_id:
        os.environ["GCP_PROJECT"] = request.project_id

    try:
        # Load the Antigravity config
        config = load_agent_config()

        # Run the agent in an asynchronous execution loop
        async with Agent(config) as agent:
            response = await agent.chat(request.prompt)
            result = await response.text()

        logger.info("Successfully generated SRE diagnostics report.")
        return DiagnoseResponse(status="success", result=result)

    except Exception as e:
        logger.exception("Failed to execute SRE diagnostics.")
        raise HTTPException(
            status_code=500,
            detail=f"SRE Agent Execution Failure: {str(e)}"
        )


@app.post("/chat")
async def chat(request: ChatRequest) -> ChatResponse:
    """Trigger a stateful agent chat request.

    Starts a new agent conversation or resumes an existing one from remote
    state persisted in Google Cloud Firestore.

    Args:
        request: The ChatRequest payload.

    Returns:
        ChatResponse containing the agent response text and active conversation ID.
    """
    logger.info(f"Received SRE chat request (conversation_id={request.conversation_id}): {request.prompt}")

    # Set project ID in environment if provided to affect the tools
    if request.project_id:
        os.environ["GCP_PROJECT"] = request.project_id

    try:
        # Load the Firestore configuration strategy
        config = load_firestore_agent_config(conversation_id=request.conversation_id)

        # Run the agent in an asynchronous execution loop
        async with Agent(config) as agent:
            response = await agent.chat(request.prompt)
            result = await response.text()
            # Retrieve the active conversation ID from the agent
            conv_id = agent.conversation_id

        logger.info(f"Successfully processed chat request. Active conversation ID: {conv_id}")
        return ChatResponse(status="success", response=result, conversation_id=conv_id)

    except Exception as e:
        logger.exception("Failed to execute SRE agent chat.")
        raise HTTPException(
            status_code=500,
            detail=f"SRE Agent Chat Execution Failure: {str(e)}"
        )
